[phases.setup]
nixPkgs = ["nodejs_22", "python311", "gcc", "gnumake"]

[phases.install]
cmds = ["rm -rf node_modules/.cache", "npm ci --force"]

[phases.build]
cmds = ["npm rebuild better-sqlite3", "npm run build"]

[start]
cmd = "npm run start"
